### ISSUE TITLE
Error connecting to server with Field Data Plugin Tool

### ISSUE THREAD

**Issue by edgarbelda** [AquaticInformatics/aquarius-field-data-framework#145]
Hi @DougSchmidt-AI 
It's been a long time since I've written to you, I hope everything is going well.

I am trying to reinstall some plugins with the tool but I get the following error when trying to connect.

`INFO: Field Data Plugin Tool v20.3.5 connected to AQTS 2018.4.80.0 on MABRACAAQD01
INFO: Disconnected from AQTS 2018.4.80.0 on MABRACAAQD01
ERROR: Cannot bind to the new display member.
Parameter name: newDisplayMember`
![mstsc_XgojoIlP7y](https://user-images.githubusercontent.com/14314396/99191772-21643300-276f-11eb-9848-1dabf3c73e0c.png)

I have tried several versions of the tool but I always get the same error.

Do you know why it could be?

**Comment by DougSchmidt-AI** [comment]
Hi @edgarbelda. Yup, it's been a while!

My best guess is it is an API version mismatch of some sort. Since the server version is still AQTS 2018.4, I'd recommend trying the latest 18.4.x release of the FieldDataPlugin tool.

https://github.com/AquaticInformatics/aquarius-field-data-framework/releases/download/v18.4.21/FieldDataPluginTool.exe

I think you can also install plugins without the special tool, using the SystemConfig page (I think that worked in 2018.4, it certainly works in newer versions).

You can browse to the SystemConfig page at http://MABRACAAQD01/AQUARIUS/SystemConfig and click the "Field Data Plugins" tab.

If neither of those options is working for you, can download and run our SystemSizer tool on the app server, according to these instructions (make sure you grab the latest SystemSizer version):

https://github.com/AquaticInformatics/getting-started/releases/tag/SystemSizer

Just downloading the EXE and running it on the app server should be enough to let the tool ZIP up the last week's worth of logs and activities and upload them to our secure SFTP server. The Support Team will be notified, and we can take a deeper look at what might be going sideways.

And I know you probably don't have much say in this, but 2018.4 is now a quite old/unsupported version of AQTS. The support window is officially "N-2", meaning that we support the current release (which is 2020.3) plus the two previous releases (the oldest being 2020.1). So it looks like KV is running a server that is more than a year outside its support window. So if you can advocate to get the servers updated, the whole project's support experience will be better.

Cheers,
Doug

**Comment by DougSchmidt-AI** [comment]
Ah, it looks like `Cannot bind to the new display member` is an exception thrown by the WinForms ListBox control used by the tool to show all the installed plugins. 

https://stackoverflow.com/questions/25761803/cannot-bind-to-the-new-display-member-in-combobox

So definitely give the SyystemConfig page a try as an alternative approach.

**Comment by edgarbelda** [comment]
Thank you very much @DougSchmidt-AI!
I tried with the FieldDataPluginTool version 18.4.21 and with the SystemConfig and it still doesn't work. It seems that there is something wrong with the server that is being used.
I have transferred to KV your suggestions to update the server and they have told me that they are studying it.
As I have more news I will tell you.

Greetings,
Edgar

**Comment by DougSchmidt-AI** [comment]
OK. I would strongly recommend that KV runs the SystemSizer tool as instructed above. It will provide a ZIP archive of last week's activity for all AQUARIUS products, and will automatically upload that ZIP to our secure SFTP site and notify the our support team when it arrives. The cause of the failure will be captured somewhere in a log file contained within that ZIP archive.

That will likely be the fastest path to a resolution. I don't think the KV team is extremely familiar with AQTS app server quirks, so it might be difficult for them to accurately diagnose an unfamiliar system behaving so far from a normal.

**Comment by DougSchmidt-AI** [comment]
@edgarbelda I'm closing this stale issue, but if it is still a problem, let me know and we'll get you and KV sorted out.

**Comment by edgarbelda** [comment]
Sure! If I detect it again, I'll let you know. Thank you very much for your help @DougSchmidt-AI
