### ISSUE TITLE
Creating and attaching another file with aquarius-field-data-framework

### ISSUE THREAD

**Issue by edgarbelda** [AquaticInformatics/aquarius-field-data-framework#49]
I'm trying to crate and attach a excel file at the same time that I parse the file.
The excel file is created with information included in the file to parse.

Is it possible to do that?

Regards,

**Comment by DougSchmidt-AI** [comment]
Yes, you can attach any other files to the visits created by your plugin, if you upload a ZIP archive containing your plugin's file and the extra files.

https://github.com/AquaticInformatics/aquarius-field-data-framework/tree/master/docs#uploading-field-data-with-attachments

For example, let's assume that you write a plugin to parse JSON data. In this example, your users will be uploading *.json files to the Springboard page.

The framework will actually accept two different files through your plugin:
- The **core file format** parsed by your plugin (JSON files in this case, but it could be a CSV file, an XML file, or some binary data that your plugin understands)
- A ZIP archive containing just one core file at its root, plus any number of extra files in subfolders within the ZIP archive. These extra files will be automatically added as visit attachments to any visits created by the core file.

### Example - Attach an Excel spreadsheet to field visit data

Let's assume that:
- your plugin can parse `Location1Friday.json` as a visit on Friday for Location 1.
- you want to attach `Location1FridayCalcs.xlsx` as an Excel spreadsheet that relates to the Friday visit.
- you also took a picture while visiting the location, and you want to attach `IMG001.jpg` to the Friday visit as well.

Create a ZIP archive named `AllMyFridayFiles.zip`, with the following contents:

```
Location1Friday.json
attachments/Location1FridayCalcs.xlsx
attachments/IMG001.jpg
```

When you drop the `AllMyFridayFiles.zip` file on the Springboard drop target, your plugin will detect its JSON file, and create a visit on Friday, plus that visit will have the image and spreadsheet attached to it, for easy viewing or downloading for later analysis.

## Notes about the ZIP attachment archive format

### 1) The ZIP archive name doesn't matter

The filename of the ZIP archive itself doesn't matter. The filename won't be imported into AQUARIUS. Only the content and filenames within the ZIP archive are important.

You could have named the file `Location1Friday.zip`, or `foo.zip`, or even `something.else`. The archive doesn't need to have a .zip extension. It just needs to be a PKZIP file.

### 2) Only the core file can exist in the archive root

The ZIP archive can have only a single file at its root, and that file must be the core file supported by your plugin.

If `foo.zip` had the following layout, the upload would fail, because there are two files at the archive root:
```
Location1Friday.json
Location1FridayCalcs.xlsx
```

You need to create the ZIP archive so that all the attachments are in a nested folder or folders within the ZIP archive.

### 3) The name of nested ZIP folders doesn't matter.

When attaching other files, only the filename will be retained. `attachments/Location1FridayCalcs.xlsx` will be attached to the Friday visit as `Location1FridayCalcs.xlsx`, and `attachments/IMG001.jpg` will be attached to the Friday visit as `IMG001.jpg`.

So the ZIP archive from note 1 could also be structured like this, and would yield the same result:

```
Location1Friday.json
folder1/Location1FridayCalcs.xlsx
folder2/IMG001.jpg
```

### 4) Be careful with multi-visit file formats. Every visit created by a core file gets a copy of every attachment in the ZIP archive.

This likely won't affect your project, but you should be aware of it.

The field data framework allows for a plugin to create multiple visits from a single file.

For example, the stock "Cross Section Survey" and "Stage Discharge Readings" plugins both accept CSV files which can create more than one visit in more than one location from a single CSV file.

When the zip-archive-with-attachments format is used, every visit will get a separate copy of every attachment.

So if your `Location1Friday.json` file could be parsed by your plugin to create two visits, one on Friday and another on Saturday, then each visit would have its own copy of the image and spreadsheet.

For small files, this doesn't really matter, but it can start to consume significant disk space if you are doing a bulk migration.

I know of one customer who was trying to use the StageDischargeReadings plugin to migrate a large set of historical field visit data, using a single 12 MB CSV file storing 8000 separate field visits. That system ran out of disk space because 8000 * 12MB = 96 GB of attachment disk space.

The workaround here was to split that 12 MB CSV file into many smaller files, to lower the duplicated attachment count.

**Comment by edgarbelda** [comment]
Thank you very much for your explanation but I think I didn't explain well.
What I would like is to be able to create some documents by processing the input file to the plugin and then attach it to the visit created by the plugin.
I attach you a workflow with the idea that I want.

If it is not possible, could you explain me how to attach a file into a visit with the  AQUARIUS SDK?

![inkscape_2019-03-12_13-49-31](https://user-images.githubusercontent.com/14314396/54201651-79dd2a80-44ce-11e9-97d3-d1c90511e504.png)

Regards.

**Comment by DougSchmidt-AI** [comment]
Thanks for the clarification. I now understand what you're wanting to achieve.

A solution is possible, but it isn't as simple as you or I would like. I'll outline it below ...

### You can't add field visit attachments from within a plugin

Ideally, you're asking for an inteface method like this to exist in the field data framework:

```C#
public interface IFieldDataResultsAppender
{
    // ... other methods ...

    void AddFieldVisitAttachment(FieldVisitInfo fieldVisit, string fileName, byte[] fileContent);
}
```

That method doesn't exist in the current release, but it definitely could be added. I think other plugins might benefit from it as well. I've added a request for that method to the dev team's backlog, but that doesn't help you right now, using 2018.4 software.

### There is no public API for uploading field visit attachments

There is a `POST /Acquisition/v2/locations/{LocationUniqueId}/attachments` API for uploading location attachments, but no equivalent API for upload field visit attachments.

Something like `POST /Acquisition/v2/fieldvisits/{FieldVisitUniqueId}/attachments`, with all the other request properties matching those in the location attachment API.

I've also added that request to the dev team's backlog, but that also doesn't help you right now.

### Something that will work in AQTS 2018.4 - Write an external uploader integration

You can write an external integration that will
- Take a FlowTracker2 file as input, plus AQTS credentials with permissions for creating field visit data
- Create the spreadsheet and PDF from the FlowTracker2 file as you proposed.
- Extract the AQTS target location identifier from the FT file (that's the Properties.SiteNumber string value from DataFile.json)
- Create a ZIP archive containing the FT file (the core file), plus the XLSX and PDF files as attachments
- Call the `GET /AQUARIUS/Publish/v2/GetLocationDescriptionList?LocationIdentier={targetLocationIdentifier}` API to get the location GUID from the `LocationDescriptions[0].UniqueId` response property.
- Call the `POST /AQUARIUS/Acquisition/v2/locations/{LocationUniqueId}/visits/upload/plugins` API to upload the ZIP file. The FlowTracker2 plugin will then parse the file, create the visit, and the XLXS and PDF files will be attached to the created visit.

Here's the C# logic that consumes the Aquarius.SDK to perform the location GUID lookup and file posting:

```C#
private void UploadZipVisit(string locationIdentifier, string zipPath)
{
    try
    {
        var server = "myappserver";
        var username = "username";
        var password = "password";

        Log.Info($"Connecting to {server} as {username} ...");

        using (var client = AquariusClient.CreateConnectedClient(server, username, password))
        {
            Log.Info($"Connected to {server} ({client.ServerVersion})");

            var location = client.Publish.Get(new LocationDescriptionListServiceRequest
                {
                    LocationIdentifier = locationIdentifier
                })
                .LocationDescriptions
                .Single();

            var response = client.Acquisition.PostFileWithRequest(zipPath, new PostVisitFile
            {
                LocationUniqueId = location.UniqueId
            });

            Log.Info($"Uploaded '{zipPath}' successfully to {location.Identifier} ({location.Name})");
        }
    }
    catch (WebServiceException exception)
    {
        Log.Error($"AQTS server error: {exception.ErrorCode} {exception.ErrorMessage}");
    }
}
```

**Comment by edgarbelda** [comment]
Thank you very much! Your explanation was really useful and detailed. Now I know all the possibilities to attach files. I will also keep an eye out for future updates and developments.

Regards

**Comment by DougSchmidt-AI** [comment]
OK, great. I'll close this issue now, but feel free to raise a new issue if you hit any roadblocks.
